### ISSUE TITLE
Image magick error for very large rasters

### ISSUE THREAD

**Issue by RichardJActon** [jokergoo/EnrichedHeatmap#58]
If your data exceed 16,000 rows or columns then it hits the default limits set by imagemagick which produces the following somewhat cryptic error:

```
Error in magick_image_write_frame(image, format = format, i = i) : 
  Image must have at least 1 frame to write a bitmap
```

This stumped me for a while and I eventually thought to increase the imagemagick resource limits having encounter a similar issue with magick before, the linked question reminded me how to do this:

https://askubuntu.com/questions/1041349/imagemagick-command-line-convert-limit-values

You just edit the contents of: /etc/ImageMagick-6/policy.xml (restart you R session for changes to take effect)

I'm not sure about non-linux systems

Perhaps the error message here could be improved to point users in the direction of adjusting the imagemagick system resource limits if they need to rasterize very large matrices?

**Comment by eggrandio** [comment]
I was getting this error when using EnrichedHeatmap trying to plot ChIP-seq data for 33k gene promoters.
```
Error in Cairo(width, height, type = "png", file = filename, pointsize = pointsize,  : 
  Failed to create Cairo backend!
```
I suggest changing the error message to "do not use raster_by_magick when more than 16000 rows are being plotted".

I was able to plot my data with `raster_resize_mat = TRUE`, although the raster does not look as "nice" as if I do `raster_by_magick = TRUE` with only 16000 rows.

**Comment by jokergoo** [comment]
Thanks! I will add this message.

I think I can internally down sample the matrix to less than 16000 rows before making the heatmap.

**Comment by gdevailly** [comment]
Same issue here. Glad you're looking into it. Best luck!

**Comment by RichardJActon** [comment]
Individually you can get around this by editing the image magic config file I mentioned in the initial issue to increase the default resource limits. I don't know if you can call magick with parameters that override these defaults which might be a way to address it from this end but if not then there is not much that can easily be done other than pointing people to how to change this config if they want to render with magick.

**Comment by jokergoo** [comment]
I think this is a machine-specific problem. I tried on my MacBook, even for a matrix with 500000 row, it worked fine.

![image](https://user-images.githubusercontent.com/449218/134865659-e7b3d68f-57fb-484d-a5e4-8c801a4bbe18.png)

I need to find a machine that can reproduce this error.

@eggrandio according to your error message, it seems a problem related to **Cairo** package. 

@RichardJActon I think it is impossible to configure via **magick** R package. One solution that I can think of is, if I can catch this error, then I can reduce the matrix by random sampling on rows and columns that is only for making the temporary raster image. One more thing I need to consider is that the raster image also supports `cell_fun`/`layer_fun`, so I need to properly take care of that if I do random sampling on the matrix.

**Comment by gdevailly** [comment]
On my side, big simple Heatmaps works well indeed, until the split option is used in draw().
Would you like a reproducible example?

**Comment by jokergoo** [comment]
@gdevailly Now I can reproduce your error. It is because the height of the temporary image is too huge, which cannot be handled by **Cairo**.

```
Browse[1]> do.call(device_fun, c(list(filename = temp_image, width = 1000, height = 1000)))
Browse[1]> do.call(device_fun, c(list(filename = temp_image, width = 1000, height = 10000)))
Browse[1]> do.call(device_fun, c(list(filename = temp_image, width = 1000, height = 100000)))
Error in Cairo(width, height, type = "png", file = filename, pointsize = pointsize,  :
  Failed to create Cairo backend!
```

My solution is if the raster image size is too huge, I will switch e.g. from `CairoPNG()` to `png()`. On the other hand, I decide to use `png()` as the default raster device.

**Comment by jokergoo** [comment]
Another experiment with `ragg::agg_png()` shows it is better to restrict the raster image with width or height less than 50k px. I think I need to improve the corresponding code.

![image](https://user-images.githubusercontent.com/449218/134875728-b67bbb51-359d-4358-b382-94efeb458a7f.png)

**Comment by jokergoo** [comment]
And for Cairo, the maximal height/width is 2^15 - 1 = 32767

**Comment by jokergoo** [comment]
@gdevailly , thanks for your reply. It would be great if you can send me the object `dataset`. I cannot find a random dataset that reproduces this error.

**Comment by gdevailly** [comment]
@jokergoo Sure thing.
Here's the dataset and a tiny Rmd document reproducing the error (I hope the drive is working :-/ ). 

https://drive.google.com/drive/folders/1SeLAcObqUqFXHrqpc-MVWC6aYxe0x7gr?usp=sharing

```r
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8       
 [4] LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] parallel  stats4    grid      stats     graphics  grDevices utils     datasets 
 [9] methods   base     

other attached packages:
[1] EnrichedHeatmap_1.22.0 GenomicRanges_1.44.0   GenomeInfoDb_1.28.1   
[4] IRanges_2.26.0         S4Vectors_0.30.0       BiocGenerics_0.38.0   
[7] ComplexHeatmap_2.8.0  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7             compiler_4.1.1         RColorBrewer_1.1-2    
 [4] XVector_0.32.0         bitops_1.0-7           iterators_1.0.13      
 [7] tools_4.1.1            zlibbioc_1.38.0        digest_0.6.27         
[10] lattice_0.20-44        evaluate_0.14          clue_0.3-59           
[13] png_0.1-7              rlang_0.4.11           foreach_1.5.1         
[16] magick_2.7.3           yaml_2.2.1             xfun_0.26             
[19] fastmap_1.1.0          GenomeInfoDbData_1.2.6 knitr_1.34            
[22] cluster_2.1.2          GlobalOptions_0.1.2    locfit_1.5-9.4        
[25] GetoptLong_1.0.5       rmarkdown_2.11         magrittr_2.0.1        
[28] codetools_0.2-18       matrixStats_0.60.1     htmltools_0.5.2       
[31] shape_1.4.6            circlize_0.4.13        colorspace_2.0-2      
[34] RCurl_1.98-1.3         doParallel_1.0.16      crayon_1.4.1          
[37] rjson_0.2.20           Cairo_1.5-12.2        
```

**Comment by jokergoo** [comment]
@gdevailly thanks for your file! I have downloaded and successfully built the rmd file. You can delete the files at any time.

On my MacBook, it only gives the error of "Failed to create Cairo backend!", but I will make more experiments.

**Comment by RichardJActon** [comment]
> I think this is a machine-specific problem. I tried on my MacBook, even for a matrix with 500000 row, it worked fine.

Maybe the ImageMagick system library has a different default system resources set in the config in the macOS distribution - I don't know what the path to the equivalent of  /etc/ImageMagick-6/policy.xml is for macOS and I don't have a mac to check.

I also got the "Failed to create Cairo backend!" that's why I originally set `raster_by_magick = TRUE` option to see if I could get it to work with different settings.  If I'm remembering correctly this error went away after I fixed the ImageMagick config.

**Comment by jokergoo** [comment]
In the old implementation, the temporary image file has a size of `a x b px` where `a` is the number of columns in the heatmap slice and `b` is the number of rows. So when the matrix is huge, `a` or `b` can be very large and they might exceed the ability of certain graphics device functions.

Now my solution to this problem is, I would restrict the maximal width or height of the temporary image to 30000px, which should be OK for most device functions (e.g. `png()` with cairo turned on, `CairoPNG()` and `agg_png()`). The maximal width and height of the temporary image can be controlled by two new global options `ht_opt$raster_temp_image_max_width` and `ht_opt$raster_temp_image_max_height`.

Also now I set `png()` as the default raster device, because the old version of **Cairo** does not work on R 4.*.

I still cannot reproduce the error related to imagemagick. Can you update the ComplexHeatmap package from GitHub and see whether you still have the error?

@gdevailly with the new version of ComplexHeatmap, the Rmd file you provided can be successfully built.

**Comment by gdevailly** [comment]
Sorry I was distracted by something else.
Still an issue with the newer ComplexHeatmap (main branch, should I install the devel branch?):

```r
## Error in magick_image_write_frame(image, format = format, i = i): Image must have at least 1 frame to write a bitmap
```

```r
sessionInfo()
## R version 4.1.1 (2021-08-10)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 20.04.3 LTS
## 
## Matrix products: default
## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
## 
## locale:
##  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
##  [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
##  [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
##  [1] parallel  stats4    grid      stats     graphics  grDevices utils    
##  [8] datasets  methods   base     
## 
## other attached packages:
## [1] EnrichedHeatmap_1.22.0 GenomicRanges_1.44.0   GenomeInfoDb_1.28.1   
## [4] IRanges_2.26.0         S4Vectors_0.30.0       BiocGenerics_0.38.0   
## [7] ComplexHeatmap_2.9.4  
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_1.0.7             highr_0.9              XVector_0.32.0        
##  [4] bslib_0.3.0            compiler_4.1.1         RColorBrewer_1.1-2    
##  [7] jquerylib_0.1.4        zlibbioc_1.38.0        bitops_1.0-7          
## [10] iterators_1.0.13       tools_4.1.1            digest_0.6.27         
## [13] lattice_0.20-45        clue_0.3-59            jsonlite_1.7.2        
## [16] evaluate_0.14          png_0.1-7              rlang_0.4.11          
## [19] foreach_1.5.1          magick_2.7.3           yaml_2.2.1            
## [22] xfun_0.26              fastmap_1.1.0          GenomeInfoDbData_1.2.6
## [25] cluster_2.1.2          stringr_1.4.0          knitr_1.34            
## [28] sass_0.4.0             GlobalOptions_0.1.2    locfit_1.5-9.4        
## [31] R6_2.5.1               GetoptLong_1.0.5       rmarkdown_2.11        
## [34] magrittr_2.0.1         codetools_0.2-18       matrixStats_0.60.1    
## [37] htmltools_0.5.2        shape_1.4.6            circlize_0.4.13       
## [40] colorspace_2.0-2       stringi_1.7.4          RCurl_1.98-1.3        
## [43] doParallel_1.0.16      crayon_1.4.1           rjson_0.2.20
```

It is indeed most likely due to some config issue in magick on my side.
```r
library(magick)
Linking to ImageMagick 6.9.10.23
Enabled features: fontconfig, freetype, fftw, lcms, pango, webp, x11
Disabled features: cairo, ghostscript, heic, raw, rsvg
Using 16 threads
```

**Comment by jokergoo** [comment]
I think I only fixed the problem of "Failed to create Cairo backend!", while not "Image must have at least 1 frame to write a bitmap" because I cannot catch the latter from my machine.

I guess I need to install a virtual machine to try it on Ubuntu...

**Comment by jokergoo** [comment]
I also saw the output from `library(magick)` on my Macbook is different from yours where cairo is enabled here:

```r
> library(magick)
Linking to ImageMagick 6.9.12.3
Enabled features: cairo, fontconfig, freetype, heic, lcms, pango, raw, rsvg, webp
Disabled features: fftw, ghostscript, x11
```

**Comment by travilucas** [comment]
Hello, this problem is still not resolved. My data exceed 16,000 rows or columns then it hits the default limits set by imagemagick which may produces the following somewhat cryptic error:
`heatmapPeaks
Error: Image must have at least 1 frame to write a bitmap`
This is my object for plotting.
Can you help me dig out what's going wrong?
[heatmapPeaks.zip](https://github.com/jokergoo/EnrichedHeatmap/files/12226426/heatmapPeaks.zip)

**Comment by LilingJiang** [comment]
@travilucas Hi, I'm getting the same error with ArchR's heatmapPeaks, have you solved it? Thx.

**Comment by NayeliGutierrez** [comment]
same error as @travilucas in ArchR with data for tutorial. Did you find any solution?
